env: gfootball

env_args:
  write_full_episode_dumps: False
  write_goal_dumps: False
  dump_freq: 0
  render: False
  time_limit: 150
  time_step: 0
  map_name: "academy_counterattack_hard"
  stacked: False
  representation: "simple115v2"
  rewards: "scoring"
  logdir: "football_dumps"
  write_video: False
  number_of_right_players_agent_controls: 0
  seed: 0


test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 10050000